
POST http://localhost:3000/class
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxMjMyOGY1LTRhMWEtNDg2NS05Zjk1LTRkMjc2ODFhMDJiOCIsInVzZXJuYW1lIjoiZGFuaWxvIiwiZW1haWwiOiJkYW5pbG9AZW1haWwuY29tIiwiaXNfdGVhY2hlciI6dHJ1ZSwiaWF0IjoxNzM4NjA5OTgyLCJleHAiOjE3Mzg2MTcxODJ9.4GhYKC-3o-vS6eTNBpLBHlzcg1kwvLPNIEe-SyN76fA

{
    "name": "Fase 1",
    "due_date": "2025-02-04",
    "url": "https://link.com",
    "points": 100,
    "type": "LEITURA",
    "teacher_id": "712328f5-4a1a-4865-9f95-4d27681a02b8",
    "extra_lesson_id": null
}

###

GET http://localhost:3000/class
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxMjMyOGY1LTRhMWEtNDg2NS05Zjk1LTRkMjc2ODFhMDJiOCIsInVzZXJuYW1lIjoiZGFuaWxvIiwiZW1haWwiOiJkYW5pbG9AZW1haWwuY29tIiwiaXNfdGVhY2hlciI6dHJ1ZSwiaWF0IjoxNzM4NjA5OTgyLCJleHAiOjE3Mzg2MTcxODJ9.4GhYKC-3o-vS6eTNBpLBHlzcg1kwvLPNIEe-SyN76fA


###

GET http://localhost:3000/class/bb3e3fa9-0087-4597-92af-0b06ad0ae633
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0M2IxNDFkLTZjZjQtNDFlMy05NzEyLWJmMDdmNThjYzgwMyIsInVzZXJuYW1lIjoic2FtcGxlMSIsImVtYWlsIjoic2FtcGxlMUBlbWFpbC5jb20iLCJpc190ZWFjaGVyIjp0cnVlLCJpYXQiOjE3Mzg2MDYzNzMsImV4cCI6MTczODYxMzU3M30.oTR9Cb7-6faKKZAgcDsAwxtvw1iBsk4CtXcUb9dtSCM

###
