
POST http://localhost:3000/lessonPlan
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlNTUzNTY5LTgwMjEtNGRmYS1hNTJkLWM0NzM4MTJiZjZjYyIsInVzZXJuYW1lIjoiSWdvciIsImVtYWlsIjoiaWdvckBnbWFpbC5jb20iLCJpc190ZWFjaGVyIjp0cnVlLCJpYXQiOjE3Mzg2MTA0NjgsImV4cCI6MTczODYxNzY2OH0.TGemzPfMWzxzwkU1rPHrhJd59iH38cImeHS0aTy6AXk

{
    "teacher_id": "712328f5-4a1a-4865-9f95-4d27681a02b8",
    "name": "Português",
    "theme": "Conjugação dos Verbos"
}

###

GET http://localhost:3000/lessonPlan
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlNTUzNTY5LTgwMjEtNGRmYS1hNTJkLWM0NzM4MTJiZjZjYyIsInVzZXJuYW1lIjoiSWdvciIsImVtYWlsIjoiaWdvckBnbWFpbC5jb20iLCJpc190ZWFjaGVyIjp0cnVlLCJpYXQiOjE3Mzg2MTA0NjgsImV4cCI6MTczODYxNzY2OH0.TGemzPfMWzxzwkU1rPHrhJd59iH38cImeHS0aTy6AXk


###

