POST http://localhost:3000/question
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxMjMyOGY1LTRhMWEtNDg2NS05Zjk1LTRkMjc2ODFhMDJiOCIsInVzZXJuYW1lIjoiZGFuaWxvIiwiZW1haWwiOiJkYW5pbG9AZW1haWwuY29tIiwiaXNfdGVhY2hlciI6dHJ1ZSwiaWF0IjoxNzM4NzEyNjI2LCJleHAiOjE3Mzg3MTk4MjZ9.KjpSWZmT0Glrh4neUy_6gkHqMQ1LSFQT3UBmZuK51ag

{
    "extra_lesson_id": "e2b6f522-ec98-49f9-852c-2d1ec759af04",
    "question": "Qual o conteúdo abordado no vídeo",
    "answer": "IA e sua influência no mundo real"
}

###


GET http://localhost:3000/question
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxMjMyOGY1LTRhMWEtNDg2NS05Zjk1LTRkMjc2ODFhMDJiOCIsInVzZXJuYW1lIjoiZGFuaWxvIiwiZW1haWwiOiJkYW5pbG9AZW1haWwuY29tIiwiaXNfdGVhY2hlciI6dHJ1ZSwiaWF0IjoxNzM4NzEyNjI2LCJleHAiOjE3Mzg3MTk4MjZ9.KjpSWZmT0Glrh4neUy_6gkHqMQ1LSFQT3UBmZuK51ag


###

GET http://localhost:3000/question
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxMjMyOGY1LTRhMWEtNDg2NS05Zjk1LTRkMjc2ODFhMDJiOCIsInVzZXJuYW1lIjoiZGFuaWxvIiwiZW1haWwiOiJkYW5pbG9AZW1haWwuY29tIiwiaXNfdGVhY2hlciI6dHJ1ZSwiaWF0IjoxNzM4NzEyNjI2LCJleHAiOjE3Mzg3MTk4MjZ9.KjpSWZmT0Glrh4neUy_6gkHqMQ1LSFQT3UBmZuK51ag


###
